// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/NorthBeachOpenMicFlyer-e_sGy6/OpenMicFlyer.tsx": () => import("../components/mockups/templates/NorthBeachOpenMicFlyer-e_sGy6/OpenMicFlyer.tsx"),
  "./components/mockups/templates/SeveranceDinnerPartyInvite-lK19qR/DinnerPartyPosterSeverance.tsx": () => import("../components/mockups/templates/SeveranceDinnerPartyInvite-lK19qR/DinnerPartyPosterSeverance.tsx")
};
